# Generated by Django 3.1.5 on 2021-01-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
